// The words and hand signals for Trick Deck's tricks, by trick id. Made by tools/trick-cues.mjs from Trick Deck's js/tricks.js.
// Trick Deck (trick-deck.junkdrawer.works) keeps each dog's progress in this browser under 'trickdeck.v1'.
export const CUES = {
  "sit": ["Sit", "Sit", "Palm up, lift your hand from waist to chest."],
  "down": ["Down", "Down", "Flat palm, lower it toward the floor."],
  "touch": ["Touch", "Touch", "Flat palm toward your dog, fingers down."],
  "leave": ["Leave it", "Leave it", "Point at the thing, then close your hand."],
  "drop": ["Drop it", "Drop it", "Open hand under their chin."],
  "come": ["Come", "Come", "Open both arms wide, then bring your hands to your chest."],
  "stay": ["Stay", "Stay", "Flat palm toward their face, like a stop sign."],
  "wait": ["Wait at the door", "Wait", "Flat palm toward them."],
  "place": ["Go to your bed", "Bed", "Point to the bed."],
  "quiet": ["Quiet", "Quiet", "Finger to your lips."],
  "settle": ["Settle", "Settle", ""],
  "shake": ["Shake", "Shake", "Open hand, palm up, below their chin."],
  "bow": ["Take a bow", "Take a bow", "Sweep one hand down to the floor."],
  "pawsup": ["Paws up", "Paws up", "Pat the object."],
  "headdown": ["Are you tired?", "Are you tired?", "Point at the floor between their paws."],
  "highfive": ["High five", "High five", "Palm facing them at nose height."],
  "pawtarget": ["Paw target", "Press", "Point to the note."],
  "wave": ["Wave", "Say bye", "Wave your hand."],
  "sitpretty": ["Sit pretty", "Sit pretty", "Raise a flat hand above their head."],
  "scratch": ["Scratch board", "Scratch", "Tap the board."],
  "covereyes": ["Cover your eyes", "Shy", "Touch your own nose."],
  "prayers": ["Say your prayers", "Say your prayers", "Bow your head."],
  "balance": ["Treat on the nose", "Leave it… Okay!", ""],
  "spin": ["Spin", "Spin", "Draw a small circle with your finger."],
  "catch": ["Catch", "Catch", ""],
  "backup": ["Back up", "Back", "Push both palms toward them."],
  "twirl": ["Twirl", "Twirl", "Circle your finger the other way."],
  "middle": ["Middle", "Middle", "Pat both thighs."],
  "jump": ["Jump over", "Over", "Sweep your arm over the bar."],
  "around": ["Around", "Around", "Point to the far side of the object."],
  "rollover": ["Roll over", "Roll over", "Roll your hand in a small circle near the floor."],
  "bang": ["Play dead", "Bang!", "Finger gun."],
  "crawl": ["Crawl", "Crawl", "Palm down, slide it along the floor."],
  "hoop": ["Through the hoop", "Hoop", "Point through the hoop."],
  "weave": ["Leg weave", "Weave", "Take a big step and point through."],
  "findit": ["Find it", "Find it", "Sweep your hand low."],
  "speak": ["Speak", "Speak", "Open and close your hand like a mouth."],
  "fetch": ["Fetch", "Fetch", "Point where it went."],
  "whichhand": ["Which hand?", "Which hand?", "Hold both fists out low."],
  "bell": ["Ring to go out", "Bell", "Point at the bell."],
  "chin": ["Chin rest", "Chin", "Cupped hand low in front of them."],
  "leash": ["Get your leash", "Get your leash", ""],
  "closedoor": ["Close the door", "Close it", "Point at the door."],
  "shell": ["Shell game", "Which one?", "Gesture at the cups."],
  "hideseek": ["Hide and seek", "Come find me!", ""],
  "toyname": ["Get it by name", "Get Bunny", ""],
  "tidy": ["Put your toys away", "Tidy up", "Point from the toy to the basket."],
};
